### ISSUE TITLE
Bug: adapter should handle when DB name is longer than 64 characters

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper-adapter-mongodb#42]
MongoDB places a 64 character limit on database names, while hyper Data does not place any limit. The Mongo adapter ought to be able to handle mapping a >64 name to a <64 character name, since it is imposing the constraint.

I think this can implemented as a hash of the provided name with some timestamp based element ie. something like a GUID, then store that on the `meta` document for the database. Then the adapter can use _that_ as the DB name.

**Comment by twilson63** [comment]
Nice work
